@startuml
header <size:23>**Casos de uso del software de encuestas y analisis de la movilidad de Puerto Madryn. **</size>
skinparam packageStyle rect
/'Actores  '/
Actor encuestador
Actor investigador

rectangle {
    left to right direction
    /'Encuestador y grupo familiar'/
    usecase CU0001 as "**Loguearse** en el sistema"
    usecase CU0002 as "Modificar encuesta 
    realizada en cierto lapso de tiempo "
    usecase CU0003 as "Encuestar grupo familiar"
    usecase CU0004 as "Autoencuestarse"
    usecase CU0005 as "Encuestar madre"
    usecase CU0006 as "Encuestar padre"
    usecase CU0007 as "Encuestar tutor/encargado"
    usecase CU0008 as "Encuestar hermanx" 
    usecase CU0009 as "Encuestar otro familiar" 
    usecase CU0010 as "Registrar datos personales 
    del/la encuestadx" 
    usecase CU0011 as "Registrar ocupacion" 
    usecase CU0012 as "Registrar estudiante" 
    usecase CU0013 as "Registrar empleado" 
    usecase CU0014 as "Registrar autonomo" 
    usecase CU0015 as "Registrar desempleado/
    en busqueda de empleo" 
    usecase CU0016 as "Registrar establecimiento en 
    el que se ocupa (Escuela u otro 
    establecimiento publico)."
    usecase CU0017 as "Registrar Genero"
    usecase CU0018 as "Registrar fecha de nacimiento"
    usecase CU0019 as "Registrar lugar de naciemiento"
    usecase CU0020 as "Registrar estudios alcanzados 
    --
    Primario incompleto
    --
    Primario completo
    --
    Secundario incompleto
    --
    Secundario completo
    --
    Terciario incompleto
    --
    Terciario completo
    --
    Universitario incompleto
    --
    Universitario completo
    --
    Otro
    "
    /'Viaje'/
    usecase CU0021 as "Registrar viaje 
    del encuestado "
    usecase CU0022 as "Registrar duración 
    de viaje "
    usecase CU0023 as "Registrar Costo 
    del viaje"
    /' usecase CU0024 as "Registrar Tramo de viaje " '/
    usecase CU0025 as "Registrar hora"
    usecase CU0026 as "Registrar Medio de
    transporte utilizado"
    usecase CU0027 as "Registrar Origen"
    usecase CU0028 as "Calle y Altura "
    usecase CU0029 as "Registrar Destino"
    usecase CU0030 as "Registrar percepción de 
    costo de viaje 1-2-3-4-5"
    usecase CU0031 as "Registrar calidad - 
    muy agradable - 
    agradable - 
    poco agradable - 
    desagradable"
    usecase CU0032 as "Registrar dias"
    /' Investigador '/
    usecase CU0033 as "Cargar Encuestador"
    usecase CU0034 as "Determinar cantidad máx de 
    viajes realizados a diferentes horas 
    de acuerdo el vehículo utilizado."
    usecase CU0035 as "Filtrar Encuestas 
    por Genero"
    usecase CU0036 as "Filtrar encuestados 
    por Destino"
    usecase CU0037 as "Filtrar encuestas 
    por Encuestador"
    usecase CU0038 as "Filtrar estudiantes 
    por **Escuela**"
    usecase CU0039 as "Filtrar encuestados 
    por **Ocupacion**"
    usecase CU0040 as "Filtrar encuestados 
    por establecimiento **Destino**"
    usecase CU0041 as "Filtrar encuestados 
    por **Lugar de Residencia**"
    usecase CU0042 as "Filtrar encuestados 
    por **Edad**"
    usecase CU0043 as "Filtrar encuestados 
    por **Genero**"
    usecase CU0044 as "Filtrar encuestados 
    por **Lugar de nacimiento**"
    usecase CU0045 as "Combinar n filtros"
    /' usecase CU0046 as "Determinar cagnt. máx de viajes realizados en diferentes franjas horarias de acuerdo al vehículo utilizado" '/
    usecase CU0047 as "Identificar Grupo familiar de encuestador"
    usecase CU0048 as "Remover encuestas duplicadas, 
    o redundantes por relevamiento de distintos
    estudiantes del mismo hogar"
    usecase CU0049 as "Determinar cantidad y modalidad 
    que finalizan en establecimientos educativos"
    usecase CU0050 as "Determinar nivel socioeconomico 
    del encuestado"
    usecase CU0051 as "Modificar encuesta"
    usecase CU0052 as "Determinar medio de 
    transporte mas utilizado"
    /' usecase CU0053 as "Determinar el nivel socioeconomico" '/
    usecase CU0054 as "Aplicar flitros"

/'Relaciones  '/
    /'Encuestar'/
    together {
        CU0010 ..>  CU0011    :<<include>> 
        CU0010 ..>  CU0016   :<<include>>
        CU0010 ..>  CU0017   :<<include>>
        CU0010 ..>  CU0018   :<<include>>
        CU0010 ..>  CU0019   :<<include>>
        CU0010 ..>  CU0020   :<<include>>
    }                        
    /'ocupacion'/           
    together {
        CU0011 ..> CU0012  :<<include>>
        CU0011 ..> CU0013  :<<include>>
        CU0011 ..> CU0014  :<<include>>
        CU0011 ..> CU0015  :<<include>>
    }
    /'Viaje  '/
    together {
        CU0021 .>  CU0022    :<<include>>
        CU0021 ..>  CU0023   :<<include>>
        /' CU0021  .>  CU0024:<<include>> '/
        CU0021 ..>  CU0025   :<<include>>
        CU0021  ..>  CU0026  :<<include>>
        CU0021  ..>  CU0027  :<<include>>
        CU0021  ..>  CU0029  :<<include>>
        CU0021  ..>  CU0030  :<<include>>
        CU0021  ..>  CU0031  :<<include>>
        CU0021  ..>  CU0032  :<<include>>
        CU0027  ..>  CU0028  :<<include>>
        CU0029  ..>  CU0028  :<<include>>
    }
    together {
    CU0004  <.. CU0003  :<<include>>
        CU0003 ..>  CU0005  :<<include>>
        CU0003 ..>  CU0006  :<<include>>
        CU0003 ..>  CU0007  :<<include>>
        CU0003 ..>  CU0008  :<<include>>
        CU0003 ..>  CU0009  :<<include>>
        CU0003 <..  CU0010   :<<include>>
    }
    together {
        /'Investigador'/
      CU0054 ..> CU0035    :<<include>>
      CU0054 ..> CU0036    :<<include>>
      CU0054 ..> CU0037    :<<include>>
      CU0054 ..> CU0038    :<<include>>
      CU0054 ..> CU0039    :<<include>>
      CU0054 ..> CU0040    :<<include>>
      CU0054 ..> CU0041    :<<include>>
      CU0054 ..> CU0042    :<<include>>
      CU0054 ..> CU0043    :<<include>> 
      CU0054 ..> CU0044    :<<include>> 
      CU0054 <.. CU0045    :<<extends>>
    }
}                       
/'loguearse'/
encuestador --- CU0001 
CU0001 ----- investigador 
CU0054 ----- investigador 
/'Mod encuesta'/
encuestador --- CU0002
encuestador --- CU0003 
encuestador --- CU0021
investigador -- CU0033    :<<include>>
investigador -- CU0034    :<<include>>
investigador -- CU0047    :<<include>>  
investigador -- CU0048    :<<include>>  
investigador -- CU0049    :<<include>>  
investigador -- CU0050    :<<include>>  
investigador -- CU0051    :<<include>>  
investigador -- CU0052    :<<include>>  

@enduml
